server:
  port: 8181
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type:
        text/html
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
  security:
    user:
      name: yif
      password: 1234


doctor:
  fileName: "C:\\\\Users\\\\admin\\\\Desktop\\\\Api\\\\医师节数据样例.xlsx"
User:
  fileName: "C:\\\\Users\\\\admin\\\\Desktop\\\\Api\\\\魔梵研发组.xlsx"