server:
  port: 8181
  servlet:
    context-path: /doctor
spring:
  datasource:
    username: root
    password: hszyf2051
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type:
        text/html
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
  security:
    user:
      name: yif
      password: 1234

doctor:
  fileName: "C:/Users/admin/Desktop/Api/医师节数据样例.xlsx"
  wrongFile: "C:/Users/admin/Desktop/Api/reload/医师节数据样例.xlsx"
  rightMsgUrl: "C:/Users/admin/Desktop/Api/sendMsgSuccess.xlsx"
  wrongMsgUrl: "C:/Users/admin/Desktop/Api/sendMsgWrong.xlsx"
  sendSuccessExcel: "C:/Users/admin/Desktop/Api/发送成功医生数据.xlsx"
  reloadWrongUrl: "C:/Users/admin/Desktop/Api/reload/sendMsgWrong.xlsx"
  corpid: wx1199888fb72190c9
  corpsecret: oUCu-DxjBNMgkT7ltCqSos7SvYOeV32beRK0SXmLjcs
  # 授权后重定向的回调链接地址，请使用urlencode对链接进行处理
  redirect_uri: https://ai.foemy.com/doctor/callBack
  #  redirect_uri: http://foemy.asuscomm.com:8181/callBack
  scope: snsapi_base
  #  snsapi_base：静默授权，可获取成员的基础信息（UserId与DeviceId）；
  #  snsapi_privateinfo：手动授权，可获取成员的详细信息，包含头像、二维码等敏感信息。
  agentid: 2
  jpgUrl: http://ai.foemy.com/doctor/images/doctor2.jpg
  # 动态监测修改的文件夹目录
#  file: "C:/Users/admin/Desktop/Api/"